// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irshgmmxdneyejxtwnsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlyc2hnbW14ZG5leWVqeHR3bnNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2MTE2OTIsImV4cCI6MjA3NDE4NzY5Mn0.1ALRtyoBi778ki2JTsGRjnIxrfHGbJpl8NjV2zd9qCo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});